version: '3'

services:
  dvwa:
    image: infoslack/dvwa
    container_name: dvwa_target
    networks:
      - waf_network

  waf_real:
    image: owasp/modsecurity-crs:3.3.2-nginx
    container_name: waf_instance1
    ports:
      - "8081:80"
    volumes:
      - ./waf_config:/etc/nginx/conf.d
    environment:
      - MODSEC_AUDIT_ENGINE=On
      - MODSEC_RULE_ENGINE=On
      - PORT=8001
    networks:
      - waf_network
    depends_on:
      - dvwa

  waf_honeypot:
    image: owasp/modsecurity-crs:3.3.2-nginx
    container_name: waf_honeypot
    ports:
      - "8088:80"
    volumes:
      - ./honeypot_config:/etc/nginx/conf.d
    environment:
      - MODSEC_AUDIT_ENGINE=On
      - PORT=8001
    networks:
      - waf_network

  waf_honeypot_2:
      image: owasp/modsecurity-crs:3.3.2-nginx
      container_name: honey_admin # Fake admin panel (For bots searching for login type pages)
      ports:
        - "8089:80"
      volumes:
        - ./honeynet_configs/admin/honey_admin.conf:/etc/nginx/templates/conf.d/default.conf.template
        - ./honeynet_configs/admin/index.html:/usr/share/nginx/html/index.html
        - ./honeynet_configs/admin_logs:/var/log/nginx
      environment:
        - MODSEC_AUDIT_ENGINE=On
      networks:
        - waf_network

  waf_honeypot_3:
      image: owasp/modsecurity-crs:3.3.2-nginx
      container_name: honey_api # Fake API endpoint (For bots searching for API endpoints)
      ports:
        - "8091:80"
      volumes:
        - ./honeynet_configs/api/honey_api.conf:/etc/nginx/templates/conf.d/default.conf.template
        - ./honeynet_configs/api_logs:/var/log/nginx
      environment:
        - MODSEC_AUDIT_ENGINE=On
      networks:
        - waf_network
networks:
  waf_network:
    driver: bridge
