server {
    listen 80;
    server_name localhost;

    default_type application/json;

    location / {
        modsecurity on;
        proxy_pass http://127.0.0.1:65535;
        error_page 502 =200 @fake_success;
    }

    location @fake_success {
        default_type application/json;
        return 200 '{"status": "running", "service": "UserDB-API"}';
    }
}