server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /login {
       modsecurity on;
       # Pretend to send data to a non-existent backend to give Modsec time to analyze
       proxy_pass http://127.0.0.1:65535;
       # When the backend is unreachable (Error 502), return a fake login response
       error_page 502 =200 @fake_login_response;
    }

    location @fake_login_response {
        default_type text/html;
        return 200 "Invalid credentials. Please try again.";
    }
}